import { z } from 'zod';
import {
  ChainSchema,
  EthAddressSchema,
  TimestampSchema,
  UuidSchema,
} from '../common/index.js';

/**
 * Signal severity levels
 */
export const SignalSeveritySchema = z.enum(['low', 'medium', 'high', 'critical']);
export type SignalSeverity = z.infer<typeof SignalSeveritySchema>;

/**
 * Recommended action types
 */
export const RecommendedActionSchema = z.enum([
  'none',
  'monitor',
  'alert',
  'reduce_exposure',
  'exit_position',
  'buy',
  'sell',
]);
export type RecommendedAction = z.infer<typeof RecommendedActionSchema>;

/**
 * Signal type identifiers
 */
export const SignalTypeSchema = z.enum([
  'LaunchDetected',
  'MoltDetected',
  'EarlyDistribution',
  'LiquidityRisk',
  'RiskAlert',
  'PriceAlert',
  'WalletActivity',
  'Custom',
]);
export type SignalType = z.infer<typeof SignalTypeSchema>;

/**
 * Signal model
 * Represents an alert or recommendation generated by a strategy
 */
export const SignalSchema = z.object({
  id: UuidSchema,
  ts: TimestampSchema,
  severity: SignalSeveritySchema,
  signalType: SignalTypeSchema.optional(),
  title: z.string().min(1).max(200),
  summary: z.string().min(1).max(2000),
  token: EthAddressSchema.optional(),
  tokenSymbol: z.string().optional(),
  chain: ChainSchema.optional(),
  wallet: EthAddressSchema.optional(),
  strategyId: z.string().min(1),
  evidence: z.array(z.object({
    type: z.string(),
    value: z.string(),
    link: z.string().url().optional(),
  })).or(z.record(z.unknown())).optional(),
  recommendedAction: RecommendedActionSchema,
  acknowledged: z.boolean().default(false),
  acknowledgedAt: TimestampSchema.optional(),
  acknowledgedBy: z.string().optional(),
  meta: z.record(z.unknown()).optional(),
});
export type Signal = z.infer<typeof SignalSchema>;

/**
 * Signal creation input
 */
export const CreateSignalSchema = SignalSchema.omit({
  id: true,
  ts: true,
  acknowledged: true,
  acknowledgedAt: true,
  acknowledgedBy: true,
});
export type CreateSignal = z.infer<typeof CreateSignalSchema>;

/**
 * Signal filter for querying
 */
export const SignalFilterSchema = z.object({
  severity: SignalSeveritySchema.optional(),
  signalType: SignalTypeSchema.optional(),
  strategyId: z.string().optional(),
  chain: ChainSchema.optional(),
  token: EthAddressSchema.optional(),
  wallet: EthAddressSchema.optional(),
  acknowledged: z.boolean().optional(),
  startTs: TimestampSchema.optional(),
  endTs: TimestampSchema.optional(),
});
export type SignalFilter = z.infer<typeof SignalFilterSchema>;

/**
 * Signal update (for acknowledgement)
 */
export const UpdateSignalSchema = z.object({
  acknowledged: z.boolean().optional(),
});
export type UpdateSignal = z.infer<typeof UpdateSignalSchema>;

/**
 * WebSocket signal message
 */
export const WsSignalMessageSchema = z.object({
  type: z.literal('signal'),
  data: SignalSchema,
});
export type WsSignalMessage = z.infer<typeof WsSignalMessageSchema>;

/**
 * WebSocket system status message
 */
export const WsSystemStatusSchema = z.object({
  type: z.literal('system_status'),
  data: z.object({
    killSwitchActive: z.boolean(),
    activeConnectors: z.number(),
    activeStrategies: z.number(),
    lastEventTs: TimestampSchema.optional(),
  }),
});
export type WsSystemStatus = z.infer<typeof WsSystemStatusSchema>;

/**
 * All WebSocket message types
 */
export const WsMessageSchema = z.discriminatedUnion('type', [
  WsSignalMessageSchema,
  WsSystemStatusSchema,
]);
export type WsMessage = z.infer<typeof WsMessageSchema>;

